export enum PokemonGeneration {
  GENERATION_ONE = 'generation-i',
  GENERATION_TWO = 'generation-ii',
  GENERATION_THREE = 'generation-iii',
  GENERATION_FOUR = 'generation-iv',
  GENERATION_FIVE = 'generation-v',
  GENERATION_SIX = 'generation-vi',
  GENERATION_SEVEN = 'generation-vii',
  GENERATION_EIGHT = 'generation-viii',
}

export enum PokemonStat {
  HP = 'hp',
  ATTACK = 'attack',
  DEFENSE = 'defense',
  SPECIAL_ATTACK = 'special-attack',
  SPECIAL_DEFENSE = 'special-defense',
  SPEED = 'speed',
}

export enum PokemonType {
  NORMAL = 'normal',
  FIGHTING = 'fighting',
  FLYING = 'flying',
  POISON = 'poison',
  GROUND = 'ground',
  ROCK = 'rock',
  BUG = 'bug',
  GHOST = 'ghost',
  STEEL = 'steel',
  FIRE = 'fire',
  WATER = 'water',
  GRASS = 'grass',
  ELECTRIC = 'electric',
  PSYCHIC = 'psychic',
  ICE = 'ice',
  DRAGON = 'dragon',
  DARK = 'dark',
  FAIRY = 'fairy',
  STELLAR = 'stellar',
}

export const GENERATION_ORDER_MAP: Record<string, number> = {
  'generation-i': 1,
  'generation-ii': 2,
  'generation-iii': 3,
  'generation-iv': 4,
  'generation-v': 5,
  'generation-vi': 6,
  'generation-vii': 7,
  'generation-viii': 8,
  'generation-ix': 9,
};

export const POKEMON_GENERATION_VALUES = Object.values(PokemonGeneration);

export const MAX_STAT_VALUE = 255;

export const ALL_POKEMONS = 1302;

export const POKEMON_STAT = ['defense', 'attack', 'speed'];

export const POKEMON_TYPES = [
  'normal',
  'fighting',
  'flying',
  'poison',
  'ground',
  'rock',
  'bug',
  'ghost',
  'steel',
  'fire',
  'water',
  'grass',
  'electric',
  'psychic',
  'ice',
  'dragon',
  'dark',
  'fairy',
  'stellar',
];

export const POKEMON_ABILITIES: string[] = [
  'stench',
  'drizzle',
  'speed-boost',
  'battle-armor',
  'sturdy',
  'damp',
  'limber',
  'sand-veil',
  'static',
  'volt-absorb',
  'water-absorb',
  'oblivious',
  'cloud-nine',
  'compound-eyes',
  'insomnia',
  'color-change',
  'immunity',
  'flash-fire',
  'shield-dust',
  'own-tempo',
  'suction-cups',
  'intimidate',
  'shadow-tag',
  'rough-skin',
  'wonder-guard',
  'levitate',
  'effect-spore',
  'synchronize',
  'clear-body',
  'natural-cure',
  'lightning-rod',
  'serene-grace',
  'swift-swim',
  'chlorophyll',
  'illuminate',
  'trace',
  'huge-power',
  'poison-point',
  'inner-focus',
  'magma-armor',
  'water-veil',
  'magnet-pull',
  'soundproof',
  'rain-dish',
  'sand-stream',
  'pressure',
  'thick-fat',
  'early-bird',
  'flame-body',
  'run-away',
  'keen-eye',
  'hyper-cutter',
  'pickup',
  'truant',
  'hustle',
  'cute-charm',
  'plus',
  'minus',
  'forecast',
  'sticky-hold',
  'shed-skin',
  'guts',
  'marvel-scale',
  'liquid-ooze',
  'overgrow',
  'blaze',
  'torrent',
  'swarm',
  'rock-head',
  'drought',
  'arena-trap',
  'vital-sprit',
  'white-smoke',
  'pure-power',
  'shell-armor',
  'air-lock',
  'tangled-feet',
  'motor-drive',
  'rivalry',
  'steadfast',
  'snow-cloak',
  'gluttony',
  'anger-point',
  'unburden',
  'heatproof',
  'simple',
  'dry-skin',
  'download',
  'iron-fist',
  'poison-heal',
  'adaptability',
  'skill-link',
  'hydration',
  'solar-power',
  'quick-feet',
  'normalize',
  'sniper',
  'magic-guard',
  'no-guard',
  'stall',
  'technician',
  'leaf-guard',
  'klutz',
  'mold-breaker',
  'super-luck',
  'aftermath',
  'anticipation',
  'forewarn',
  'unaware',
  'tinted-lens',
  'filter',
  'slow-start',
  'scrappy',
  'storm-drain',
  'ice-body',
  'solid-rock',
  'snow-warning',
  'honey-gather',
  'frisk',
  'reckless',
  'multitype',
  'flower-gift',
  'bad-dreams',
  'pickpocket',
  'sheer-force',
  'contrary',
  'unnerve',
  'defiant',
  'defeatist',
  'cursed-body',
  'healer',
  'friend-guard',
  'weak-armor',
  'heavy-metal',
  'light-metal',
  'multiscale',
  'toxic-boost',
  'flare-boost',
  'harvest',
  'telepathy',
  'moody',
  'overcoat',
  'poison-touch',
  'regenerator',
  'big-pecks',
  'sand-rush',
  'wonder-skin',
  'analytic',
  'illusion',
  'imposter',
  'infiltrator',
  'mummy',
  'moxie',
  'justified',
  'rattled',
  'magic-bounce',
  'sap-sipper',
  'prankster',
  'sand-force',
  'iron-barbs',
  'zen-mode',
  'victory-star',
  'turboblaze',
  'teravolt',
  'aroma-veil',
  'flower-veil',
  'cheek-pouch',
  'protean',
  'fur-coat',
  'magician',
  'bulletproof',
  'competitive',
  'strong-jaw',
  'refrigerate',
  'sweet-veil',
  'stance-change',
  'gale-wings',
  'mega-launcher',
  'grass-pelt',
  'symbiosis',
  'tough-claws',
  'pixilate',
  'gooey',
  'aerilate',
  'parental-bond',
  'dark-aura',
  'fairy-aura',
  'aura-break',
  'primordial-sea',
  'desolate-land',
  'delta-stream',
  'stamina',
  'wimp-out',
  'emergency-exit',
  'water-compaction',
  'merciless',
  'shields-down',
  'stakeout',
  'water-bubble',
  'steelworker',
  'berserk',
  'slush-rush',
  'long-reach',
  'liquid-voice',
  'triage',
  'galvanize',
  'surge-surfer',
  'schooling',
  'disguise',
  'battle-bond',
  'power-construct',
  'corrosion',
  'comatose',
  'queenly-majesty',
  'innards-out',
  'dancer',
  'battery',
  'fluffy',
  'dazzling',
  'soul-heart',
  'tangling-hair',
  'receiver',
  'power-of-alchemy',
  'beast-boost',
  'rks-system',
  'electric-surge',
  'psychic-surge',
  'misty-surge',
  'grassy-surge',
  'full-metal-body',
  'shadow-shield',
  'prism-armor',
  'neuroforce',
  'intrepid-sword',
  'dauntless-shield',
  'libero',
  'ball-fetch',
  'cotton-down',
  'propeller-tail',
  'mirror-armor',
  'gulp-missile',
  'stalwart',
  'steam-engine',
  'punk-rock',
  'sand-spit',
  'ice-scales',
  'ripen',
  'ice-face',
  'power-spot',
  'mimicry',
  'screen-cleaner',
  'steely-spirit',
  'perish-body',
  'wandering-spirit',
  'gorilla-tactics',
  'neutralizing-gas',
  'pastel-veil',
  'hunger-switch',
  'quick-draw',
  'unseen-fist',
  'curious-medicine',
  'transistor',
  'dragons-maw',
  'chilling-neigh',
  'grim-neigh',
  'as-one-glastrier',
  'as-one-spectrier',
  'lingering-aroma',
  'seed-sower',
  'thermal-exchange',
  'anger-shell',
  'purifying-salt',
  'well-baked-body',
  'wind-rider',
  'guard-dog',
  'rocky-payload',
  'wind-power',
  'zero-to-hero',
  'commander',
  'electromorphosis',
  'protosynthesis',
  'quark-drive',
  'good-as-gold',
  'vessel-of-ruin',
  'sword-of-ruin',
  'tablets-of-ruin',
  'beads-of-ruin',
  'orichalcum-pulse',
  'hadron-engine',
  'opportunist',
  'cud-chew',
  'sharpness',
  'supreme-overlord',
  'costar',
  'toxic-debris',
  'armor-tail',
  'earth-eater',
  'mycelium-might',
  'minds-eye',
  'supersweet-syrup',
  'hospitality',
  'toxic-chain',
  'embody-aspect',
  'tera-shift',
  'tera-shell',
  'teraform-zero',
  'poison-puppeteer',
  'mountaineer',
  'wave-rider',
  'skater',
  'thrust',
  'perception',
  'parry',
  'instinct',
  'dodge',
  'jagged-edge',
  'frostbite',
  'tenacity',
  'pride',
  'deep-sleep',
  'power-nap',
  'spirit',
  'warm-blanket',
  'gulp',
  'herbivore',
  'sandpit',
  'hot-blooded',
  'medic',
  'life-force',
  'lunchbox',
  'nurse',
  'melee',
  'sponge',
  'bodyguard',
  'hero',
  'last-bastion',
  'stealth',
  'vanguard',
  'nomad',
  'sequence',
  'grass-cloak',
  'celebrate',
  'lullaby',
  'calming',
  'daze',
  'frighten',
  'interference',
  'mood-maker',
  'confidence',
  'fortune',
  'bonanza',
  'explode',
  'omnipotent',
  'share',
  'black-hole',
  'shadow-dash',
  'sprint',
  'disgust',
  'high-rise',
  'climber',
  'flame-boost',
  'aqua-boost',
  'run-up',
  'conqueror',
  'shackle',
  'decoy',
  'shield',
];
